# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20160227_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance', models.BooleanField()),
                ('week_talk', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
        migrations.RemoveField(
            model_name='kid',
            name='assistance',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='week_talk',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AddField(
            model_name='leader',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='school.School'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='team.Kid'),
        ),
    ]
