# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20160607_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='team.Team'),
        ),
    ]
